# Deep Coding Agent Configuration Template
# 
# To use this configuration:
# 1. Copy this file to ~/.deep-coding-config.json (note: .json extension, not .yml)
# 2. Convert YAML format to JSON format
# 3. Or use the CLI commands to set configuration values
#
# Example CLI commands to set up ARK API:
# deep-coding config --set arkApiKey="c3d86f5e-2861-4eff-b05c-cb2e9fa04f42"
# deep-coding config --set apiBaseURL="https://ark.cn-beijing.volces.com/api/v3"
# deep-coding config --set apiModel="ep-20250617155129-hfzl9"
# deep-coding config --set aiProvider="openai"

# JSON Configuration Example:
{
  "defaultLanguage": "go",
  "outputFormat": "text",
  "analysisDepth": 3,
  "backupOnRefactor": true,
  "excludePatterns": [
    "node_modules/**",
    "vendor/**",
    "dist/**",
    "build/**",
    ".git/**",
    "coverage/**",
    "*.min.js",
    "*.min.css"
  ],
  "aiProvider": "openai",
  "openaiApiKey": "",
  "arkApiKey": "c3d86f5e-2861-4eff-b05c-cb2e9fa04f42",
  "apiBaseUrl": "https://ark.cn-beijing.volces.com/api/v3",
  "apiModel": "ep-20250617155129-hfzl9",
  "tavilyApiKey": "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",
  "customSettings": {},
  "lastUpdated": "2025-06-27T00:13:47.222968+08:00"
}